/* The following code was generated by JFlex 1.4.3 on 13/11/21 2:44 */

package proyecto_catedra_ayc01t_sl190836_ml190272;
import java_cup.runtime.Symbol;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 13/11/21 2:44 from the specification file
 * <tt>C:/Users/jony2/Documents/NetBeansProjects/ReposAYC-Project-CodeMain/src/proyecto_catedra_ayc01t_sl190836_ml190272/LexerCup.flex</tt>
 */
class LexerCup implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  3,  5,  0,  0,  3,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     3, 37,  0,  0,  0,  0,  0, 27, 28, 29, 25,  0,  3, 47, 46,  4, 
     2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  0, 34, 36, 38, 35,  0, 
     0,  8, 22,  6, 17, 18, 11, 41,  7, 15, 43, 40, 12, 19, 16, 13, 
    24, 44,  9, 23, 14, 21, 10, 26, 42, 20,  1, 32,  0, 33,  0, 45, 
     0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 30, 39, 31,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\1\22\2\1\4\1\2"+
    "\1\5\1\6\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\2\15\1\1\1\15\1\1\3\2\1\16\1\3\12\2"+
    "\1\17\16\2\1\20\2\2\1\21\4\2\1\22\1\2"+
    "\1\23\1\2\1\24\1\25\10\2\1\26\14\2\1\27"+
    "\11\2\1\0\2\2\1\30\12\2\1\31\2\2\1\20"+
    "\1\32\1\33\14\2\1\34\11\2\1\35\7\2\1\36"+
    "\6\2\1\37\12\2\1\40\6\2\1\41\7\2\1\42"+
    "\5\2\1\0\1\43\2\2\1\36\2\2\1\44\12\2"+
    "\1\45\2\2\1\46\1\2\1\47\1\50\3\2\1\51"+
    "\1\2\1\24\1\52\1\2\1\53\1\2\1\54\1\2"+
    "\1\55\3\2\1\56\1\57\1\2\1\60\6\2\1\61"+
    "\2\2\1\62\5\2\1\63\12\2\1\64\11\2\1\65"+
    "\1\66\1\2\1\67\1\2\1\70\1\71\5\2\1\72"+
    "\1\73\1\2\1\74\2\2\1\75\1\2\1\76\1\2"+
    "\1\77\1\100\2\2\1\101\1\2\1\102\14\2\1\103"+
    "\1\2\1\104\2\2\1\105\1\106\3\2\1\107\1\110"+
    "\1\2\1\111\1\112\1\113\1\114\1\115\1\116\2\2"+
    "\1\117\1\120\1\121\2\2\1\122\4\2\1\123\7\2"+
    "\1\124\1\125\1\126\1\127\1\130\1\131\1\2\1\132"+
    "\1\133\1\134\1\2\1\135\1\2\1\136\2\2\1\137"+
    "\2\2\1\140\2\2\1\141\1\142\1\143\1\2\1\144"+
    "\1\2\1\145\1\2\1\146\1\147\2\2\1\150\1\151"+
    "\2\2\1\152\3\2\1\153";

  private static int [] zzUnpackAction() {
    int [] result = new int[406];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\60\0\140\0\220\0\300\0\360\0\u0120\0\u0150"+
    "\0\u0180\0\u01b0\0\u01e0\0\u0210\0\u0240\0\u0270\0\u02a0\0\u02d0"+
    "\0\u0300\0\u0330\0\u0360\0\u0390\0\u03c0\0\u03f0\0\u0420\0\60"+
    "\0\u0450\0\60\0\u0480\0\60\0\60\0\60\0\60\0\60"+
    "\0\60\0\u04b0\0\u04e0\0\u04b0\0\60\0\u0510\0\u0540\0\u0570"+
    "\0\u05a0\0\60\0\u05d0\0\u0600\0\u0630\0\u0660\0\u0690\0\u06c0"+
    "\0\u06f0\0\u0720\0\u0750\0\u0780\0\u07b0\0\u07e0\0\u0810\0\u0840"+
    "\0\u0870\0\u08a0\0\u08d0\0\u0900\0\u0930\0\u0960\0\u0990\0\u09c0"+
    "\0\u09f0\0\u0a20\0\u0a50\0\u0a80\0\u0ab0\0\u0ae0\0\u0b10\0\u0b40"+
    "\0\u0b70\0\u0ba0\0\u0bd0\0\u0c00\0\140\0\u0c30\0\140\0\u0c60"+
    "\0\u0c90\0\140\0\u0cc0\0\u0cf0\0\u0d20\0\u0d50\0\u0d80\0\u0db0"+
    "\0\u0de0\0\u0e10\0\140\0\u0e40\0\u0e70\0\u0ea0\0\u0ed0\0\u0f00"+
    "\0\u0f30\0\u0f60\0\u0f90\0\u0fc0\0\u0ff0\0\u1020\0\u1050\0\140"+
    "\0\u1080\0\u10b0\0\u10e0\0\u1110\0\u1140\0\u1170\0\u11a0\0\u11d0"+
    "\0\u1200\0\u1230\0\u1260\0\u1290\0\140\0\u12c0\0\u12f0\0\u1320"+
    "\0\u1350\0\u1380\0\u13b0\0\u13e0\0\u1410\0\u1440\0\u1470\0\140"+
    "\0\u14a0\0\u14d0\0\140\0\140\0\140\0\u1500\0\u1530\0\u1560"+
    "\0\u1590\0\u15c0\0\u15f0\0\u1620\0\u1650\0\u1680\0\u16b0\0\u16e0"+
    "\0\u1710\0\u1740\0\u1770\0\u17a0\0\u17d0\0\u1800\0\u1830\0\u1860"+
    "\0\u1890\0\u18c0\0\u18f0\0\u1920\0\u1950\0\u1980\0\u19b0\0\u19e0"+
    "\0\u1a10\0\u1a40\0\u1a70\0\u1aa0\0\u1ad0\0\u1b00\0\u1b30\0\u1b60"+
    "\0\u1b90\0\u1bc0\0\140\0\u1bf0\0\u1c20\0\u1c50\0\u1c80\0\u1cb0"+
    "\0\u1ce0\0\u1d10\0\u1d40\0\u07e0\0\u1d70\0\140\0\u1da0\0\u1dd0"+
    "\0\u1e00\0\u1e30\0\u1e60\0\u1e90\0\140\0\u1ec0\0\u1ef0\0\u1f20"+
    "\0\u1f50\0\u1f80\0\u1fb0\0\u1fe0\0\140\0\u2010\0\u2040\0\u2070"+
    "\0\u20a0\0\u20d0\0\u2100\0\140\0\u2130\0\u2160\0\140\0\u2190"+
    "\0\u21c0\0\140\0\u21f0\0\u2220\0\u2250\0\u2280\0\u22b0\0\u22e0"+
    "\0\u2310\0\u2340\0\u2370\0\u23a0\0\140\0\u23d0\0\u2400\0\140"+
    "\0\u2430\0\140\0\140\0\u2460\0\u2490\0\u24c0\0\140\0\u24f0"+
    "\0\140\0\140\0\u2520\0\140\0\u2550\0\140\0\u2580\0\140"+
    "\0\u25b0\0\u25e0\0\u2610\0\140\0\140\0\u2640\0\140\0\u2670"+
    "\0\u26a0\0\u26d0\0\u2700\0\u2730\0\u2760\0\140\0\u2790\0\u27c0"+
    "\0\140\0\u27f0\0\u2820\0\u2850\0\u2880\0\u28b0\0\140\0\u28e0"+
    "\0\u2910\0\u2940\0\u2970\0\u29a0\0\u29d0\0\u2a00\0\u2a30\0\u2a60"+
    "\0\u2a90\0\140\0\u2ac0\0\u2af0\0\u2b20\0\u2b50\0\u2b80\0\u2bb0"+
    "\0\u2be0\0\u2c10\0\u2c40\0\140\0\60\0\u2c70\0\140\0\u2ca0"+
    "\0\140\0\140\0\u2cd0\0\u2d00\0\u2d30\0\u2d60\0\u2d90\0\140"+
    "\0\140\0\u2dc0\0\140\0\u2df0\0\u2e20\0\140\0\u2e50\0\140"+
    "\0\u2e80\0\140\0\140\0\u2eb0\0\u2ee0\0\140\0\u2f10\0\140"+
    "\0\u2f40\0\u2f70\0\u2fa0\0\u2fd0\0\u3000\0\u3030\0\u3060\0\u3090"+
    "\0\u30c0\0\u30f0\0\u3120\0\u3150\0\140\0\u3180\0\140\0\u31b0"+
    "\0\u31e0\0\140\0\140\0\u3210\0\u3240\0\u3270\0\140\0\140"+
    "\0\u32a0\0\140\0\140\0\140\0\140\0\140\0\140\0\u32d0"+
    "\0\u3300\0\140\0\140\0\140\0\u3330\0\u3360\0\140\0\u3390"+
    "\0\u33c0\0\u33f0\0\u3420\0\140\0\u3450\0\u3480\0\u34b0\0\u34e0"+
    "\0\u3510\0\u3540\0\u3570\0\140\0\140\0\140\0\140\0\140"+
    "\0\140\0\u35a0\0\140\0\140\0\140\0\u35d0\0\140\0\u3600"+
    "\0\140\0\u3630\0\u3660\0\140\0\u3690\0\u36c0\0\140\0\u36f0"+
    "\0\u3720\0\140\0\140\0\140\0\u3750\0\140\0\u3780\0\140"+
    "\0\u37b0\0\140\0\140\0\u37e0\0\u3810\0\140\0\u3840\0\u3870"+
    "\0\u38a0\0\140\0\u38d0\0\u3900\0\u3930\0\140";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[406];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\4\1\5\1\4\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\3\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\1\33\1\34\1\35\1\36\1\37"+
    "\1\40\1\41\1\42\1\43\1\44\1\45\1\46\1\47"+
    "\1\50\1\3\1\51\2\3\1\52\1\2\61\0\2\3"+
    "\3\0\23\3\1\0\1\3\15\0\6\3\5\0\1\4"+
    "\1\0\1\4\56\0\1\53\54\0\2\3\3\0\1\3"+
    "\1\54\1\55\1\56\3\3\1\57\13\3\1\0\1\3"+
    "\15\0\6\3\3\0\2\3\3\0\2\3\1\60\20\3"+
    "\1\0\1\3\15\0\6\3\3\0\2\3\3\0\4\3"+
    "\1\61\1\62\1\63\3\3\1\64\1\65\5\3\1\66"+
    "\1\3\1\0\1\3\15\0\6\3\3\0\2\3\3\0"+
    "\7\3\1\67\1\3\1\70\2\3\1\71\2\3\1\72"+
    "\3\3\1\0\1\3\15\0\6\3\3\0\2\3\3\0"+
    "\2\3\1\73\6\3\1\74\11\3\1\0\1\3\15\0"+
    "\6\3\3\0\2\3\3\0\2\3\1\75\1\76\2\3"+
    "\1\77\1\100\1\3\1\101\5\3\1\102\3\3\1\0"+
    "\1\3\15\0\6\3\3\0\2\3\3\0\11\3\1\103"+
    "\2\3\1\104\6\3\1\0\1\3\15\0\6\3\3\0"+
    "\2\3\3\0\3\3\1\105\1\106\3\3\1\107\1\3"+
    "\1\110\4\3\1\111\3\3\1\0\1\3\15\0\6\3"+
    "\3\0\2\3\3\0\1\3\1\112\1\113\1\114\3\3"+
    "\1\115\6\3\1\116\4\3\1\0\1\3\15\0\6\3"+
    "\3\0\2\3\3\0\5\3\1\117\1\120\3\3\1\121"+
    "\6\3\1\122\1\3\1\0\1\3\15\0\6\3\3\0"+
    "\2\3\3\0\1\123\1\3\1\124\1\3\1\125\2\3"+
    "\1\126\4\3\1\127\2\3\1\130\3\3\1\0\1\3"+
    "\15\0\6\3\3\0\2\3\3\0\2\3\1\131\1\132"+
    "\3\3\1\133\1\3\1\134\2\3\1\135\6\3\1\0"+
    "\1\3\15\0\6\3\3\0\2\3\3\0\6\3\1\136"+
    "\3\3\1\137\10\3\1\0\1\3\15\0\2\3\1\140"+
    "\3\3\3\0\2\3\3\0\2\3\1\141\4\3\1\142"+
    "\1\3\1\143\11\3\1\0\1\3\15\0\6\3\3\0"+
    "\2\3\3\0\12\3\1\144\6\3\1\145\1\146\1\0"+
    "\1\3\15\0\6\3\3\0\2\3\3\0\14\3\1\147"+
    "\1\3\1\150\4\3\1\0\1\3\15\0\6\3\3\0"+
    "\2\3\3\0\1\3\1\151\6\3\1\152\3\3\1\153"+
    "\1\3\1\154\1\155\3\3\1\0\1\3\15\0\6\3"+
    "\3\0\2\3\3\0\3\3\1\156\17\3\1\0\1\3"+
    "\15\0\6\3\3\0\2\3\3\0\1\3\1\157\1\3"+
    "\1\160\5\3\1\161\11\3\1\0\1\3\15\0\6\3"+
    "\61\0\1\162\46\0\1\45\54\0\1\45\2\0\1\45"+
    "\60\0\1\45\11\0\2\3\3\0\14\3\1\163\6\3"+
    "\1\0\1\3\15\0\6\3\3\0\2\3\3\0\3\3"+
    "\1\164\3\3\1\165\13\3\1\0\1\3\15\0\6\3"+
    "\3\0\2\3\3\0\7\3\1\166\13\3\1\0\1\3"+
    "\15\0\6\3\2\0\5\53\1\0\52\53\1\0\2\3"+
    "\3\0\2\3\1\167\11\3\1\170\6\3\1\0\1\3"+
    "\15\0\6\3\3\0\2\3\3\0\21\3\1\171\1\3"+
    "\1\0\1\3\15\0\6\3\3\0\2\3\3\0\7\3"+
    "\1\172\4\3\1\173\6\3\1\0\1\3\15\0\6\3"+
    "\3\0\2\3\3\0\6\3\1\174\3\3\1\175\4\3"+
    "\1\176\3\3\1\0\1\3\15\0\6\3\3\0\2\3"+
    "\3\0\4\3\1\177\16\3\1\0\1\3\15\0\6\3"+
    "\3\0\2\3\3\0\23\3\1\0\1\3\15\0\1\3"+
    "\1\200\4\3\3\0\2\3\3\0\10\3\1\201\12\3"+
    "\1\0\1\3\15\0\6\3\3\0\2\3\3\0\10\3"+
    "\1\202\12\3\1\0\1\3\15\0\6\3\3\0\2\3"+
    "\3\0\13\3\1\203\7\3\1\0\1\3\15\0\6\3"+
    "\3\0\2\3\3\0\13\3\1\204\7\3\1\0\1\3"+
    "\15\0\6\3\3\0\2\3\3\0\1\205\22\3\1\0"+
    "\1\3\15\0\6\3\3\0\2\3\3\0\17\3\1\206"+
    "\3\3\1\0\1\207\15\0\6\3\3\0\2\3\3\0"+
    "\23\3\1\0\1\3\15\0\1\3\1\210\4\3\3\0"+
    "\2\3\3\0\12\3\1\211\6\3\1\212\1\3\1\0"+
    "\1\3\15\0\6\3\3\0\2\3\3\0\6\3\1\213"+
    "\14\3\1\0\1\3\15\0\6\3\3\0\2\3\3\0"+
    "\3\3\1\214\2\3\1\215\14\3\1\0\1\3\15\0"+
    "\6\3\3\0\2\3\3\0\14\3\1\216\6\3\1\0"+
    "\1\3\15\0\6\3\3\0\2\3\3\0\6\3\1\217"+
    "\14\3\1\0\1\3\15\0\6\3\3\0\2\3\3\0"+
    "\7\3\1\220\13\3\1\0\1\3\15\0\6\3\3\0"+
    "\2\3\3\0\7\3\1\221\13\3\1\0\1\3\15\0"+
    "\6\3\3\0\2\3\3\0\3\3\1\222\17\3\1\0"+
    "\1\3\15\0\6\3\3\0\2\3\3\0\3\3\1\223"+
    "\17\3\1\0\1\3\15\0\6\3\3\0\2\3\3\0"+
    "\6\3\1\224\3\3\1\225\10\3\1\0\1\3\15\0"+
    "\6\3\3\0\2\3\3\0\23\3\1\0\1\3\15\0"+
    "\1\226\5\3\3\0\2\3\3\0\5\3\1\227\15\3"+
    "\1\0\1\3\15\0\6\3\3\0\2\3\3\0\13\3"+
    "\1\230\7\3\1\0\1\3\15\0\6\3\3\0\2\3"+
    "\3\0\14\3\1\231\6\3\1\0\1\3\15\0\6\3"+
    "\3\0\2\3\3\0\1\3\1\232\21\3\1\0\1\3"+
    "\15\0\6\3\3\0\2\3\3\0\6\3\1\233\14\3"+
    "\1\0\1\3\15\0\6\3\3\0\2\3\3\0\10\3"+
    "\1\234\12\3\1\0\1\3\15\0\6\3\3\0\2\3"+
    "\3\0\14\3\1\235\6\3\1\0\1\3\15\0\6\3"+
    "\3\0\2\3\3\0\20\3\1\236\2\3\1\0\1\3"+
    "\15\0\6\3\3\0\2\3\3\0\2\3\1\237\6\3"+
    "\1\240\5\3\1\241\3\3\1\0\1\3\15\0\6\3"+
    "\3\0\2\3\3\0\22\3\1\242\1\0\1\3\15\0"+
    "\6\3\3\0\2\3\3\0\11\3\1\243\11\3\1\0"+
    "\1\3\15\0\6\3\3\0\2\3\3\0\10\3\1\244"+
    "\1\3\1\245\1\246\5\3\1\247\1\3\1\0\1\3"+
    "\15\0\6\3\3\0\2\3\3\0\1\3\1\250\21\3"+
    "\1\0\1\3\15\0\6\3\3\0\2\3\3\0\10\3"+
    "\1\251\12\3\1\0\1\3\15\0\6\3\3\0\2\3"+
    "\3\0\2\3\1\252\20\3\1\0\1\3\15\0\6\3"+
    "\3\0\2\3\3\0\10\3\1\203\12\3\1\0\1\3"+
    "\15\0\6\3\3\0\2\3\3\0\23\3\1\0\1\253"+
    "\15\0\6\3\3\0\2\3\3\0\6\3\1\254\6\3"+
    "\1\255\5\3\1\0\1\3\15\0\6\3\3\0\2\3"+
    "\3\0\10\3\1\256\12\3\1\0\1\3\15\0\6\3"+
    "\3\0\2\3\3\0\7\3\1\257\13\3\1\0\1\3"+
    "\15\0\6\3\3\0\2\3\3\0\21\3\1\260\1\3"+
    "\1\0\1\3\15\0\6\3\3\0\2\3\3\0\1\261"+
    "\4\3\1\262\1\263\12\3\1\264\1\3\1\0\1\3"+
    "\15\0\6\3\3\0\2\3\3\0\21\3\1\265\1\3"+
    "\1\0\1\3\15\0\6\3\3\0\2\3\3\0\13\3"+
    "\1\266\7\3\1\0\1\3\15\0\6\3\3\0\2\3"+
    "\3\0\1\267\10\3\1\270\11\3\1\0\1\3\15\0"+
    "\6\3\3\0\2\3\3\0\23\3\1\0\1\3\15\0"+
    "\2\3\1\200\3\3\3\0\2\3\3\0\12\3\1\271"+
    "\1\272\7\3\1\0\1\3\15\0\6\3\3\0\2\3"+
    "\3\0\12\3\1\200\10\3\1\0\1\3\15\0\6\3"+
    "\3\0\2\3\3\0\11\3\1\273\11\3\1\0\1\3"+
    "\15\0\6\3\3\0\2\3\3\0\11\3\1\274\2\3"+
    "\1\275\6\3\1\0\1\3\15\0\6\3\3\0\2\3"+
    "\3\0\13\3\1\276\7\3\1\0\1\3\15\0\6\3"+
    "\3\0\2\3\3\0\10\3\1\277\12\3\1\0\1\3"+
    "\15\0\1\3\1\300\4\3\3\0\2\3\3\0\7\3"+
    "\1\301\13\3\1\0\1\3\15\0\6\3\3\0\2\3"+
    "\3\0\2\3\1\302\20\3\1\0\1\3\15\0\6\3"+
    "\3\0\2\3\3\0\2\3\1\303\3\3\1\304\1\3"+
    "\1\305\12\3\1\0\1\3\15\0\6\3\3\0\2\3"+
    "\3\0\21\3\1\306\1\3\1\0\1\3\15\0\6\3"+
    "\3\0\2\3\3\0\15\3\1\200\5\3\1\0\1\3"+
    "\15\0\6\3\3\0\2\3\3\0\11\3\1\307\11\3"+
    "\1\0\1\3\15\0\6\3\3\0\2\3\3\0\14\3"+
    "\1\310\6\3\1\0\1\3\15\0\6\3\3\0\2\3"+
    "\3\0\11\3\1\311\11\3\1\0\1\3\15\0\6\3"+
    "\3\0\2\3\3\0\10\3\1\312\12\3\1\0\1\3"+
    "\15\0\6\3\4\0\1\313\56\0\2\3\3\0\16\3"+
    "\1\314\4\3\1\0\1\3\15\0\6\3\3\0\2\3"+
    "\3\0\7\3\1\315\13\3\1\0\1\3\15\0\6\3"+
    "\3\0\2\3\3\0\11\3\1\316\11\3\1\0\1\3"+
    "\15\0\6\3\3\0\2\3\3\0\3\3\1\317\6\3"+
    "\1\320\10\3\1\0\1\3\15\0\6\3\3\0\2\3"+
    "\3\0\1\321\22\3\1\0\1\3\15\0\6\3\3\0"+
    "\2\3\3\0\14\3\1\322\6\3\1\0\1\3\15\0"+
    "\6\3\3\0\2\3\3\0\21\3\1\323\1\3\1\0"+
    "\1\3\15\0\6\3\3\0\2\3\3\0\2\3\1\324"+
    "\20\3\1\0\1\3\15\0\6\3\3\0\2\3\3\0"+
    "\17\3\1\325\3\3\1\0\1\3\15\0\6\3\3\0"+
    "\2\3\3\0\12\3\1\326\6\3\1\327\1\3\1\0"+
    "\1\3\15\0\6\3\3\0\2\3\3\0\12\3\1\330"+
    "\10\3\1\0\1\3\15\0\6\3\3\0\2\3\3\0"+
    "\11\3\1\331\11\3\1\0\1\3\15\0\6\3\3\0"+
    "\2\3\3\0\14\3\1\332\6\3\1\0\1\3\15\0"+
    "\6\3\3\0\2\3\3\0\14\3\1\333\6\3\1\0"+
    "\1\3\15\0\6\3\3\0\2\3\3\0\12\3\1\334"+
    "\10\3\1\0\1\3\15\0\6\3\3\0\2\3\3\0"+
    "\21\3\1\335\1\3\1\0\1\3\15\0\6\3\3\0"+
    "\2\3\3\0\1\3\1\227\21\3\1\0\1\3\15\0"+
    "\6\3\3\0\2\3\3\0\2\3\1\336\20\3\1\0"+
    "\1\3\15\0\6\3\3\0\2\3\3\0\14\3\1\337"+
    "\6\3\1\0\1\3\15\0\6\3\3\0\2\3\3\0"+
    "\14\3\1\340\6\3\1\0\1\3\15\0\6\3\3\0"+
    "\2\3\3\0\1\123\22\3\1\0\1\3\15\0\6\3"+
    "\3\0\2\3\3\0\17\3\1\341\3\3\1\0\1\3"+
    "\15\0\6\3\3\0\2\3\3\0\23\3\1\0\1\342"+
    "\15\0\6\3\3\0\2\3\3\0\21\3\1\241\1\3"+
    "\1\0\1\3\15\0\6\3\3\0\2\3\3\0\15\3"+
    "\1\343\5\3\1\0\1\3\15\0\6\3\3\0\2\3"+
    "\3\0\2\3\1\344\20\3\1\0\1\3\15\0\6\3"+
    "\3\0\2\3\3\0\14\3\1\345\6\3\1\0\1\3"+
    "\15\0\6\3\3\0\2\3\3\0\21\3\1\346\1\3"+
    "\1\0\1\3\15\0\6\3\3\0\2\3\3\0\6\3"+
    "\1\347\14\3\1\0\1\3\15\0\6\3\3\0\2\3"+
    "\3\0\1\350\22\3\1\0\1\3\15\0\6\3\3\0"+
    "\2\3\3\0\14\3\1\351\6\3\1\0\1\3\15\0"+
    "\6\3\3\0\2\3\3\0\10\3\1\352\12\3\1\0"+
    "\1\3\15\0\6\3\3\0\2\3\3\0\14\3\1\353"+
    "\6\3\1\0\1\3\15\0\6\3\3\0\2\3\3\0"+
    "\3\3\1\354\17\3\1\0\1\3\15\0\6\3\3\0"+
    "\2\3\3\0\14\3\1\355\6\3\1\0\1\3\15\0"+
    "\6\3\3\0\2\3\3\0\16\3\1\356\4\3\1\0"+
    "\1\3\15\0\6\3\3\0\2\3\3\0\14\3\1\357"+
    "\6\3\1\0\1\3\15\0\6\3\3\0\2\3\3\0"+
    "\12\3\1\360\10\3\1\0\1\3\15\0\6\3\3\0"+
    "\2\3\3\0\6\3\1\361\14\3\1\0\1\3\15\0"+
    "\6\3\3\0\2\3\3\0\12\3\1\362\10\3\1\0"+
    "\1\3\15\0\6\3\3\0\2\3\3\0\23\3\1\0"+
    "\1\3\15\0\1\3\1\363\4\3\3\0\2\3\3\0"+
    "\14\3\1\364\6\3\1\0\1\3\15\0\6\3\3\0"+
    "\2\3\3\0\14\3\1\365\6\3\1\0\1\3\15\0"+
    "\6\3\3\0\2\3\3\0\23\3\1\0\1\3\15\0"+
    "\1\366\5\3\3\0\2\3\3\0\7\3\1\367\4\3"+
    "\1\370\6\3\1\0\1\3\15\0\6\3\3\0\2\3"+
    "\3\0\14\3\1\371\6\3\1\0\1\3\15\0\6\3"+
    "\3\0\2\3\3\0\14\3\1\372\6\3\1\0\1\3"+
    "\15\0\6\3\3\0\2\3\3\0\14\3\1\373\6\3"+
    "\1\0\1\3\15\0\6\3\3\0\2\3\3\0\2\3"+
    "\1\374\20\3\1\0\1\3\15\0\6\3\3\0\2\3"+
    "\3\0\17\3\1\375\3\3\1\0\1\3\15\0\6\3"+
    "\3\0\2\3\3\0\3\3\1\214\17\3\1\0\1\3"+
    "\15\0\6\3\3\0\2\3\3\0\6\3\1\376\14\3"+
    "\1\0\1\3\15\0\6\3\3\0\2\3\3\0\14\3"+
    "\1\377\6\3\1\0\1\3\15\0\6\3\3\0\2\3"+
    "\3\0\2\3\1\u0100\20\3\1\0\1\3\15\0\6\3"+
    "\3\0\2\3\3\0\22\3\1\u0101\1\0\1\3\15\0"+
    "\6\3\3\0\2\3\3\0\10\3\1\u0102\12\3\1\0"+
    "\1\3\15\0\6\3\3\0\2\3\3\0\6\3\1\u0103"+
    "\2\3\1\u0104\11\3\1\0\1\3\15\0\6\3\3\0"+
    "\2\3\3\0\2\3\1\u0105\20\3\1\0\1\3\15\0"+
    "\6\3\3\0\2\3\3\0\14\3\1\u0106\6\3\1\0"+
    "\1\3\15\0\6\3\3\0\2\3\3\0\14\3\1\u0107"+
    "\6\3\1\0\1\3\15\0\6\3\3\0\2\3\3\0"+
    "\14\3\1\u0108\6\3\1\0\1\3\15\0\6\3\3\0"+
    "\2\3\3\0\21\3\1\u0109\1\3\1\0\1\3\15\0"+
    "\6\3\3\0\2\3\3\0\14\3\1\u010a\6\3\1\0"+
    "\1\3\15\0\6\3\3\0\2\3\3\0\11\3\1\u010b"+
    "\11\3\1\0\1\3\15\0\6\3\3\0\2\3\3\0"+
    "\7\3\1\u010c\13\3\1\0\1\3\15\0\4\3\1\u010d"+
    "\1\3\3\0\2\3\3\0\12\3\1\u010e\10\3\1\0"+
    "\1\3\15\0\6\3\3\0\2\3\3\0\2\3\1\u010f"+
    "\20\3\1\0\1\3\15\0\6\3\3\0\2\3\3\0"+
    "\23\3\1\0\1\u0110\15\0\6\3\3\0\2\3\3\0"+
    "\11\3\1\u0111\11\3\1\0\1\3\15\0\6\3\3\0"+
    "\2\3\3\0\23\3\1\0\1\u0112\15\0\6\3\3\0"+
    "\2\3\3\0\3\3\1\u0113\17\3\1\0\1\3\15\0"+
    "\6\3\3\0\2\3\3\0\3\3\1\u0114\17\3\1\0"+
    "\1\3\15\0\6\3\3\0\2\3\3\0\14\3\1\u0115"+
    "\6\3\1\0\1\3\15\0\6\3\3\0\2\3\3\0"+
    "\10\3\1\u0116\12\3\1\0\1\3\15\0\6\3\3\0"+
    "\2\3\3\0\7\3\1\u0117\2\3\1\u0118\2\3\1\u0119"+
    "\5\3\1\0\1\3\15\0\6\3\3\0\2\3\3\0"+
    "\3\3\1\u011a\17\3\1\0\1\3\15\0\6\3\3\0"+
    "\2\3\3\0\10\3\1\u011b\12\3\1\0\1\3\15\0"+
    "\6\3\3\0\2\3\3\0\1\3\1\u011c\21\3\1\0"+
    "\1\3\15\0\6\3\4\0\1\313\32\0\1\u011d\23\0"+
    "\2\3\3\0\17\3\1\u011e\3\3\1\0\1\3\15\0"+
    "\6\3\3\0\2\3\3\0\12\3\1\u011f\10\3\1\0"+
    "\1\3\15\0\6\3\3\0\2\3\3\0\23\3\1\0"+
    "\1\3\15\0\1\3\1\u0120\4\3\3\0\2\3\3\0"+
    "\23\3\1\0\1\3\15\0\1\u0121\5\3\3\0\2\3"+
    "\3\0\21\3\1\u0122\1\3\1\0\1\3\15\0\6\3"+
    "\3\0\2\3\3\0\10\3\1\u0123\12\3\1\0\1\3"+
    "\15\0\6\3\3\0\2\3\3\0\15\3\1\u0124\5\3"+
    "\1\0\1\3\15\0\6\3\3\0\2\3\3\0\14\3"+
    "\1\u0125\6\3\1\0\1\3\15\0\6\3\3\0\2\3"+
    "\3\0\10\3\1\u0126\12\3\1\0\1\3\15\0\6\3"+
    "\3\0\2\3\3\0\10\3\1\200\12\3\1\0\1\3"+
    "\15\0\6\3\3\0\2\3\3\0\12\3\1\u0127\10\3"+
    "\1\0\1\3\15\0\6\3\3\0\2\3\3\0\3\3"+
    "\1\u0128\17\3\1\0\1\3\15\0\6\3\3\0\2\3"+
    "\3\0\3\3\1\u0129\17\3\1\0\1\3\15\0\6\3"+
    "\3\0\2\3\3\0\13\3\1\200\7\3\1\0\1\3"+
    "\15\0\6\3\3\0\2\3\3\0\15\3\1\u012a\5\3"+
    "\1\0\1\3\15\0\6\3\3\0\2\3\3\0\10\3"+
    "\1\u012b\12\3\1\0\1\3\15\0\6\3\3\0\2\3"+
    "\3\0\14\3\1\u012c\6\3\1\0\1\3\15\0\6\3"+
    "\3\0\2\3\3\0\10\3\1\317\12\3\1\0\1\3"+
    "\15\0\6\3\3\0\2\3\3\0\11\3\1\u012d\11\3"+
    "\1\0\1\3\15\0\6\3\3\0\2\3\3\0\10\3"+
    "\1\u012e\12\3\1\0\1\3\15\0\6\3\3\0\2\3"+
    "\3\0\10\3\1\u012f\12\3\1\0\1\3\15\0\6\3"+
    "\3\0\2\3\3\0\3\3\1\u0130\17\3\1\0\1\3"+
    "\15\0\6\3\3\0\2\3\3\0\3\3\1\u0131\17\3"+
    "\1\0\1\3\15\0\6\3\3\0\2\3\3\0\3\3"+
    "\1\u0132\17\3\1\0\1\3\15\0\6\3\3\0\2\3"+
    "\3\0\14\3\1\u0133\6\3\1\0\1\3\15\0\6\3"+
    "\3\0\2\3\3\0\21\3\1\u0134\1\3\1\0\1\3"+
    "\15\0\6\3\3\0\2\3\3\0\23\3\1\0\1\3"+
    "\15\0\1\3\1\u0135\4\3\3\0\2\3\3\0\14\3"+
    "\1\u0136\6\3\1\0\1\3\15\0\6\3\3\0\2\3"+
    "\3\0\3\3\1\u0137\17\3\1\0\1\3\15\0\6\3"+
    "\3\0\2\3\3\0\3\3\1\u0138\17\3\1\0\1\3"+
    "\15\0\6\3\3\0\2\3\3\0\23\3\1\0\1\3"+
    "\15\0\2\3\1\204\3\3\3\0\2\3\3\0\3\3"+
    "\1\u0139\17\3\1\0\1\3\15\0\6\3\3\0\2\3"+
    "\3\0\3\3\1\317\17\3\1\0\1\3\15\0\6\3"+
    "\3\0\2\3\3\0\3\3\1\u013a\17\3\1\0\1\3"+
    "\15\0\6\3\3\0\2\3\3\0\3\3\1\u013b\17\3"+
    "\1\0\1\3\15\0\6\3\3\0\2\3\3\0\20\3"+
    "\1\u013c\2\3\1\0\1\3\15\0\6\3\3\0\2\3"+
    "\3\0\11\3\1\u013d\11\3\1\0\1\3\15\0\6\3"+
    "\3\0\2\3\3\0\2\3\1\u013e\20\3\1\0\1\3"+
    "\15\0\6\3\3\0\2\3\3\0\15\3\1\u013f\5\3"+
    "\1\0\1\3\15\0\6\3\3\0\2\3\3\0\17\3"+
    "\1\u0140\3\3\1\0\1\3\15\0\6\3\3\0\2\3"+
    "\3\0\10\3\1\u0141\12\3\1\0\1\3\15\0\6\3"+
    "\3\0\2\3\3\0\22\3\1\u0142\1\0\1\3\15\0"+
    "\6\3\3\0\2\3\3\0\10\3\1\u0143\12\3\1\0"+
    "\1\3\15\0\6\3\3\0\2\3\3\0\16\3\1\317"+
    "\4\3\1\0\1\3\15\0\6\3\3\0\2\3\3\0"+
    "\5\3\1\u0144\15\3\1\0\1\3\15\0\6\3\3\0"+
    "\2\3\3\0\12\3\1\u0145\10\3\1\0\1\3\15\0"+
    "\6\3\3\0\2\3\3\0\17\3\1\u0146\3\3\1\0"+
    "\1\3\15\0\6\3\3\0\2\3\3\0\23\3\1\0"+
    "\1\3\15\0\1\3\1\u0147\4\3\3\0\2\3\3\0"+
    "\10\3\1\u0148\12\3\1\0\1\3\15\0\6\3\3\0"+
    "\2\3\3\0\14\3\1\u0149\6\3\1\0\1\3\15\0"+
    "\6\3\3\0\2\3\3\0\12\3\1\u014a\10\3\1\0"+
    "\1\3\15\0\6\3\3\0\2\3\3\0\10\3\1\u014b"+
    "\12\3\1\0\1\3\15\0\6\3\3\0\2\3\3\0"+
    "\1\u014c\22\3\1\0\1\3\15\0\6\3\3\0\2\3"+
    "\3\0\1\u014d\22\3\1\0\1\3\15\0\6\3\3\0"+
    "\2\3\3\0\14\3\1\u014e\6\3\1\0\1\3\15\0"+
    "\6\3\3\0\2\3\3\0\3\3\1\u014f\17\3\1\0"+
    "\1\3\15\0\6\3\3\0\2\3\3\0\10\3\1\u0150"+
    "\12\3\1\0\1\3\15\0\6\3\3\0\2\3\3\0"+
    "\2\3\1\u0151\20\3\1\0\1\3\15\0\6\3\3\0"+
    "\2\3\3\0\14\3\1\u0152\6\3\1\0\1\3\15\0"+
    "\6\3\3\0\2\3\3\0\14\3\1\u0153\6\3\1\0"+
    "\1\3\15\0\6\3\3\0\2\3\3\0\22\3\1\u0154"+
    "\1\0\1\3\15\0\6\3\3\0\2\3\3\0\14\3"+
    "\1\u0155\6\3\1\0\1\3\15\0\6\3\3\0\2\3"+
    "\3\0\14\3\1\u0156\6\3\1\0\1\3\15\0\6\3"+
    "\3\0\2\3\3\0\12\3\1\u0157\10\3\1\0\1\3"+
    "\15\0\6\3\3\0\2\3\3\0\1\u0158\22\3\1\0"+
    "\1\3\15\0\6\3\3\0\2\3\3\0\3\3\1\u0159"+
    "\17\3\1\0\1\3\15\0\6\3\3\0\2\3\3\0"+
    "\23\3\1\0\1\3\15\0\1\3\1\u015a\4\3\3\0"+
    "\2\3\3\0\14\3\1\u015b\6\3\1\0\1\3\15\0"+
    "\6\3\3\0\2\3\3\0\21\3\1\u015c\1\3\1\0"+
    "\1\3\15\0\6\3\3\0\2\3\3\0\23\3\1\0"+
    "\1\3\15\0\1\3\1\u015d\4\3\3\0\2\3\3\0"+
    "\11\3\1\u015e\11\3\1\0\1\3\15\0\6\3\3\0"+
    "\2\3\3\0\21\3\1\u015f\1\3\1\0\1\3\15\0"+
    "\6\3\3\0\2\3\3\0\2\3\1\u0160\20\3\1\0"+
    "\1\3\15\0\6\3\3\0\2\3\3\0\14\3\1\u0161"+
    "\6\3\1\0\1\3\15\0\6\3\3\0\2\3\3\0"+
    "\4\3\1\u0162\14\3\1\u0163\1\3\1\0\1\3\15\0"+
    "\6\3\3\0\2\3\3\0\10\3\1\u0164\12\3\1\0"+
    "\1\3\15\0\6\3\3\0\2\3\3\0\2\3\1\u0165"+
    "\20\3\1\0\1\3\15\0\6\3\3\0\2\3\3\0"+
    "\11\3\1\u0166\11\3\1\0\1\3\15\0\6\3\3\0"+
    "\2\3\3\0\2\3\1\u0167\20\3\1\0\1\3\15\0"+
    "\6\3\3\0\2\3\3\0\12\3\1\u0168\10\3\1\0"+
    "\1\3\15\0\6\3\3\0\2\3\3\0\3\3\1\u0169"+
    "\17\3\1\0\1\3\15\0\6\3\3\0\2\3\3\0"+
    "\2\3\1\u016a\20\3\1\0\1\3\15\0\6\3\3\0"+
    "\2\3\3\0\6\3\1\u016b\14\3\1\0\1\3\15\0"+
    "\6\3\3\0\2\3\3\0\14\3\1\u016c\6\3\1\0"+
    "\1\3\15\0\6\3\3\0\2\3\3\0\10\3\1\u016d"+
    "\12\3\1\0\1\3\15\0\6\3\3\0\2\3\3\0"+
    "\21\3\1\u016e\1\3\1\0\1\3\15\0\6\3\3\0"+
    "\2\3\3\0\16\3\1\u016f\4\3\1\0\1\3\15\0"+
    "\6\3\3\0\2\3\3\0\14\3\1\u0170\6\3\1\0"+
    "\1\3\15\0\6\3\3\0\2\3\3\0\14\3\1\u0171"+
    "\6\3\1\0\1\3\15\0\6\3\3\0\2\3\3\0"+
    "\14\3\1\u0172\6\3\1\0\1\3\15\0\6\3\3\0"+
    "\2\3\3\0\1\3\1\u0173\21\3\1\0\1\3\15\0"+
    "\6\3\3\0\2\3\3\0\10\3\1\u0174\12\3\1\0"+
    "\1\3\15\0\6\3\3\0\2\3\3\0\15\3\1\u0175"+
    "\5\3\1\0\1\3\15\0\6\3\3\0\2\3\3\0"+
    "\3\3\1\u0176\17\3\1\0\1\3\15\0\6\3\3\0"+
    "\2\3\3\0\10\3\1\u0177\12\3\1\0\1\3\15\0"+
    "\6\3\3\0\2\3\3\0\2\3\1\u0178\20\3\1\0"+
    "\1\3\15\0\6\3\3\0\2\3\3\0\12\3\1\u0179"+
    "\10\3\1\0\1\3\15\0\6\3\3\0\2\3\3\0"+
    "\7\3\1\u017a\13\3\1\0\1\3\15\0\6\3\3\0"+
    "\2\3\3\0\1\u017b\22\3\1\0\1\3\15\0\6\3"+
    "\3\0\2\3\3\0\3\3\1\u017c\17\3\1\0\1\3"+
    "\15\0\6\3\3\0\2\3\3\0\2\3\1\u017d\20\3"+
    "\1\0\1\3\15\0\6\3\3\0\2\3\3\0\14\3"+
    "\1\u017e\6\3\1\0\1\3\15\0\6\3\3\0\2\3"+
    "\3\0\6\3\1\u017f\14\3\1\0\1\3\15\0\6\3"+
    "\3\0\2\3\3\0\1\317\22\3\1\0\1\3\15\0"+
    "\6\3\3\0\2\3\3\0\21\3\1\u0180\1\3\1\0"+
    "\1\3\15\0\6\3\3\0\2\3\3\0\1\u0181\22\3"+
    "\1\0\1\3\15\0\6\3\3\0\2\3\3\0\14\3"+
    "\1\u0182\6\3\1\0\1\3\15\0\6\3\3\0\2\3"+
    "\3\0\6\3\1\317\14\3\1\0\1\3\15\0\6\3"+
    "\3\0\2\3\3\0\10\3\1\u0183\12\3\1\0\1\3"+
    "\15\0\6\3\3\0\2\3\3\0\12\3\1\351\10\3"+
    "\1\0\1\3\15\0\6\3\3\0\2\3\3\0\16\3"+
    "\1\u0184\4\3\1\0\1\3\15\0\6\3\3\0\2\3"+
    "\3\0\11\3\1\u0185\11\3\1\0\1\3\15\0\6\3"+
    "\3\0\2\3\3\0\12\3\1\u0186\10\3\1\0\1\3"+
    "\15\0\6\3\3\0\2\3\3\0\10\3\1\u0187\12\3"+
    "\1\0\1\3\15\0\6\3\3\0\2\3\3\0\6\3"+
    "\1\u0188\14\3\1\0\1\3\15\0\6\3\3\0\2\3"+
    "\3\0\1\u0189\22\3\1\0\1\3\15\0\6\3\3\0"+
    "\2\3\3\0\14\3\1\u018a\6\3\1\0\1\3\15\0"+
    "\6\3\3\0\2\3\3\0\10\3\1\u018b\12\3\1\0"+
    "\1\3\15\0\6\3\3\0\2\3\3\0\12\3\1\u018c"+
    "\10\3\1\0\1\3\15\0\6\3\3\0\2\3\3\0"+
    "\11\3\1\u018d\11\3\1\0\1\3\15\0\6\3\3\0"+
    "\2\3\3\0\10\3\1\u018e\12\3\1\0\1\3\15\0"+
    "\6\3\3\0\2\3\3\0\10\3\1\u018f\12\3\1\0"+
    "\1\3\15\0\6\3\3\0\2\3\3\0\7\3\1\u0190"+
    "\13\3\1\0\1\3\15\0\6\3\3\0\2\3\3\0"+
    "\23\3\1\0\1\3\15\0\5\3\1\u0191\3\0\2\3"+
    "\3\0\12\3\1\u0192\10\3\1\0\1\3\15\0\6\3"+
    "\3\0\2\3\3\0\10\3\1\u0193\12\3\1\0\1\3"+
    "\15\0\6\3\3\0\2\3\3\0\16\3\1\u0194\4\3"+
    "\1\0\1\3\15\0\6\3\3\0\2\3\3\0\22\3"+
    "\1\u0195\1\0\1\3\15\0\6\3\3\0\2\3\3\0"+
    "\14\3\1\u0196\6\3\1\0\1\3\15\0\6\3\2\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[14688];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\25\1\1\11\1\1\1\11\1\1\6\11"+
    "\3\1\1\11\4\1\1\11\107\1\1\0\130\1\1\0"+
    "\121\1\1\11\171\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[406];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    private Symbol symbol(int type, Object value){
        return new Symbol(type, yyline, yycolumn, value);
    }
    private Symbol symbol(int type){
        return new Symbol(type, yyline, yycolumn);
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  LexerCup(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  LexerCup(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 63: 
          { return new Symbol(sym.OUTER, yychar, yyline, yytext());
          }
        case 108: break;
        case 103: 
          { return new Symbol(sym.DISTINCT, yychar, yyline, yytext());
          }
        case 109: break;
        case 32: 
          { return new Symbol(sym.END, yychar, yyline, yytext());
          }
        case 110: break;
        case 99: 
          { return new Symbol(sym.PRIMARY, yychar, yyline, yytext());
          }
        case 111: break;
        case 6: 
          { return new Symbol(sym.Parentesis_a, yychar, yyline, yytext());
          }
        case 112: break;
        case 13: 
          { return new Symbol(sym.Op_relacional, yychar, yyline, yytext());
          }
        case 113: break;
        case 30: 
          { return new Symbol(sym.T_dato, yychar, yyline, yytext());
          }
        case 114: break;
        case 29: 
          { return new Symbol(sym.OUT, yychar, yyline, yytext());
          }
        case 115: break;
        case 88: 
          { return new Symbol(sym.UNIQUE, yychar, yyline, yytext());
          }
        case 116: break;
        case 50: 
          { return new Symbol(sym.DROP, yychar, yyline, yytext());
          }
        case 117: break;
        case 4: 
          { return new Symbol(sym.All, yychar, yyline, yytext());
          }
        case 118: break;
        case 84: 
          { return new Symbol(sym.DELETE, yychar, yyline, yytext());
          }
        case 119: break;
        case 42: 
          { return new Symbol(sym.LR, yychar, yyline, yytext());
          }
        case 120: break;
        case 28: 
          { return new Symbol(sym.FOR, yychar, yyline, yytext());
          }
        case 121: break;
        case 71: 
          { return new Symbol(sym.PRIOR, yychar, yyline, yytext());
          }
        case 122: break;
        case 19: 
          { return new Symbol(sym.IF, yychar, yyline, yytext());
          }
        case 123: break;
        case 57: 
          { return new Symbol(sym.CROSS, yychar, yyline, yytext());
          }
        case 124: break;
        case 16: 
          { return new Symbol(sym.Op_logico, yychar, yyline, yytext());
          }
        case 125: break;
        case 33: 
          { return new Symbol(sym.USE, yychar, yyline, yytext());
          }
        case 126: break;
        case 44: 
          { return new Symbol(sym.ONLY, yychar, yyline, yytext());
          }
        case 127: break;
        case 67: 
          { return new Symbol(sym.UNION, yychar, yyline, yytext());
          }
        case 128: break;
        case 53: 
          { return new Symbol(sym.WITH, yychar, yyline, yytext());
          }
        case 129: break;
        case 20: 
          { return new Symbol(sym.C_seleccion, yychar, yyline, yytext());
          }
        case 130: break;
        case 92: 
          { return new Symbol(sym.SYSTEM, yychar, yyline, yytext());
          }
        case 131: break;
        case 22: 
          { return new Symbol(sym.DO, yychar, yyline, yytext());
          }
        case 132: break;
        case 8: 
          { return new Symbol(sym.Llave_a, yychar, yyline, yytext());
          }
        case 133: break;
        case 90: 
          { return new Symbol(sym.SEARCH, yychar, yyline, yytext());
          }
        case 134: break;
        case 3: 
          { /*Ignore*/
          }
        case 135: break;
        case 39: 
          { return new Symbol(sym.VIEW, yychar, yyline, yytext());
          }
        case 136: break;
        case 34: 
          { return new Symbol(sym.SET, yychar, yyline, yytext());
          }
        case 137: break;
        case 43: 
          { return new Symbol(sym.OVER, yychar, yyline, yytext());
          }
        case 138: break;
        case 105: 
          { return new Symbol(sym.CONSTRAINT, yychar, yyline, yytext());
          }
        case 139: break;
        case 82: 
          { return new Symbol(sym.OTHERS, yychar, yyline, yytext());
          }
        case 140: break;
        case 40: 
          { return new Symbol(sym.FROM, yychar, yyline, yytext());
          }
        case 141: break;
        case 102: 
          { return new Symbol(sym.DATABASE, yychar, yyline, yytext());
          }
        case 142: break;
        case 75: 
          { return new Symbol(sym.GROUP, yychar, yyline, yytext());
          }
        case 143: break;
        case 74: 
          { return new Symbol(sym.WRITE, yychar, yyline, yytext());
          }
        case 144: break;
        case 87: 
          { return new Symbol(sym.MODIFY, yychar, yyline, yytext());
          }
        case 145: break;
        case 80: 
          { return new Symbol(sym.RENAME, yychar, yyline, yytext());
          }
        case 146: break;
        case 12: 
          { return new Symbol(sym.P_coma, yychar, yyline, yytext());
          }
        case 147: break;
        case 96: 
          { return new Symbol(sym.NATURAL, yychar, yyline, yytext());
          }
        case 148: break;
        case 27: 
          { return new Symbol(sym.T_order, yychar, yyline, yytext());
          }
        case 149: break;
        case 1: 
          { return new Symbol(sym.ERROR, yychar, yyline, yytext());
          }
        case 150: break;
        case 5: 
          { return new Symbol(sym.COMILLA, yychar, yyline, yytext());
          }
        case 151: break;
        case 106: 
          { return new Symbol(sym.TRANSACTION, yychar, yyline, yytext());
          }
        case 152: break;
        case 23: 
          { return new Symbol(sym.BY, yychar, yyline, yytext());
          }
        case 153: break;
        case 101: 
          { return new Symbol(sym.INTERVAL, yychar, yyline, yytext());
          }
        case 154: break;
        case 49: 
          { return new Symbol(sym.NULL, yychar, yyline, yytext());
          }
        case 155: break;
        case 78: 
          { return new Symbol(sym.COLUMN, yychar, yyline, yytext());
          }
        case 156: break;
        case 18: 
          { return new Symbol(sym.TO, yychar, yyline, yytext());
          }
        case 157: break;
        case 60: 
          { return new Symbol(sym.RESET, yychar, yyline, yytext());
          }
        case 158: break;
        case 62: 
          { return new Symbol(sym.ORDER, yychar, yyline, yytext());
          }
        case 159: break;
        case 104: 
          { return new Symbol(sym.INTERSECT, yychar, yyline, yytext());
          }
        case 160: break;
        case 97: 
          { return new Symbol(sym.DECLARE, yychar, yyline, yytext());
          }
        case 161: break;
        case 79: 
          { return new Symbol(sym.HAVING, yychar, yyline, yytext());
          }
        case 162: break;
        case 41: 
          { return new Symbol(sym.FULL, yychar, yyline, yytext());
          }
        case 163: break;
        case 95: 
          { return new Symbol(sym.TRIGGER, yychar, yyline, yytext());
          }
        case 164: break;
        case 72: 
          { return new Symbol(sym.PRINT, yychar, yyline, yytext());
          }
        case 165: break;
        case 37: 
          { return new Symbol(sym.ROWS, yychar, yyline, yytext());
          }
        case 166: break;
        case 83: 
          { return new Symbol(sym.INSERT, yychar, yyline, yytext());
          }
        case 167: break;
        case 14: 
          { return new Symbol(sym.POINT, yychar, yyline, yytext());
          }
        case 168: break;
        case 65: 
          { return new Symbol(sym.ILIKE, yychar, yyline, yytext());
          }
        case 169: break;
        case 38: 
          { return new Symbol(sym.RULE, yychar, yyline, yytext());
          }
        case 170: break;
        case 73: 
          { return new Symbol(sym.WHERE, yychar, yyline, yytext());
          }
        case 171: break;
        case 2: 
          { return new Symbol(sym.Identificador, yychar, yyline, yytext());
          }
        case 172: break;
        case 11: 
          { return new Symbol(sym.Corchete_c, yychar, yyline, yytext());
          }
        case 173: break;
        case 70: 
          { return new Symbol(sym.START, yychar, yyline, yytext());
          }
        case 174: break;
        case 15: 
          { return new Symbol(sym.AS, yychar, yyline, yytext());
          }
        case 175: break;
        case 36: 
          { return new Symbol(sym.CASE, yychar, yyline, yytext());
          }
        case 176: break;
        case 59: 
          { return new Symbol(sym.ALTER, yychar, yyline, yytext());
          }
        case 177: break;
        case 51: 
          { return new Symbol(sym.ELSE, yychar, yyline, yytext());
          }
        case 178: break;
        case 89: 
          { return new Symbol(sym.UPDATE, yychar, yyline, yytext());
          }
        case 179: break;
        case 25: 
          { return new Symbol(sym.FUN, yychar, yyline, yytext());
          }
        case 180: break;
        case 31: 
          { return new Symbol(sym.NEW, yychar, yyline, yytext());
          }
        case 181: break;
        case 58: 
          { return new Symbol(sym.AFTER, yychar, yyline, yytext());
          }
        case 182: break;
        case 48: 
          { return new Symbol(sym.INTO, yychar, yyline, yytext());
          }
        case 183: break;
        case 21: 
          { return new Symbol(sym.IS, yychar, yyline, yytext());
          }
        case 184: break;
        case 86: 
          { return new Symbol(sym.EXISTS, yychar, yyline, yytext());
          }
        case 185: break;
        case 61: 
          { return new Symbol(sym.FIRST, yychar, yyline, yytext());
          }
        case 186: break;
        case 55: 
          { return new Symbol(sym.JOIN, yychar, yyline, yytext());
          }
        case 187: break;
        case 76: 
          { return new Symbol(sym.CHANGE, yychar, yyline, yytext());
          }
        case 188: break;
        case 85: 
          { return new Symbol(sym.EXCEPT, yychar, yyline, yytext());
          }
        case 189: break;
        case 7: 
          { return new Symbol(sym.Parentesis_c, yychar, yyline, yytext());
          }
        case 190: break;
        case 9: 
          { return new Symbol(sym.Llave_c, yychar, yyline, yytext());
          }
        case 191: break;
        case 45: 
          { return new Symbol(sym.THEN, yychar, yyline, yytext());
          }
        case 192: break;
        case 52: 
          { return new Symbol(sym.SHOW, yychar, yyline, yytext());
          }
        case 193: break;
        case 46: 
          { return new Symbol(sym.BOOL, yychar, yyline, yytext());
          }
        case 194: break;
        case 98: 
          { return new Symbol(sym.DEFAULT, yychar, yyline, yytext());
          }
        case 195: break;
        case 94: 
          { return new Symbol(sym.FOREIGN, yychar, yyline, yytext());
          }
        case 196: break;
        case 66: 
          { return new Symbol(sym.INNER, yychar, yyline, yytext());
          }
        case 197: break;
        case 35: 
          { return new Symbol(sym.KEY, yychar, yyline, yytext());
          }
        case 198: break;
        case 47: 
          { return new Symbol(sym.TYPE, yychar, yyline, yytext());
          }
        case 199: break;
        case 77: 
          { return new Symbol(sym.CREATE, yychar, yyline, yytext());
          }
        case 200: break;
        case 64: 
          { return new Symbol(sym.TABLE, yychar, yyline, yytext());
          }
        case 201: break;
        case 17: 
          { return new Symbol(sym.ON, yychar, yyline, yytext());
          }
        case 202: break;
        case 100: 
          { return new Symbol(sym.FUNCTION, yychar, yyline, yytext());
          }
        case 203: break;
        case 54: 
          { return new Symbol(sym.Numero, yychar, yyline, yytext());
          }
        case 204: break;
        case 91: 
          { return new Symbol(sym.SELECT, yychar, yyline, yytext());
          }
        case 205: break;
        case 81: 
          { return new Symbol(sym.VALUES, yychar, yyline, yytext());
          }
        case 206: break;
        case 93: 
          { return new Symbol(sym.CONNECT, yychar, yyline, yytext());
          }
        case 207: break;
        case 26: 
          { return new Symbol(sym.ADD, yychar, yyline, yytext());
          }
        case 208: break;
        case 56: 
          { return new Symbol(sym.CHECK, yychar, yyline, yytext());
          }
        case 209: break;
        case 68: 
          { return new Symbol(sym.USING, yychar, yyline, yytext());
          }
        case 210: break;
        case 24: 
          { return new Symbol(sym.GO, yychar, yyline, yytext());
          }
        case 211: break;
        case 107: 
          { return new Symbol(sym.CONSTRAINT_TYPE, yychar, yyline, yytext());
          }
        case 212: break;
        case 69: 
          { return new Symbol(sym.BEGIN, yychar, yyline, yytext());
          }
        case 213: break;
        case 10: 
          { return new Symbol(sym.Corchete_a, yychar, yyline, yytext());
          }
        case 214: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
