
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Nov 13 02:44:11 CST 2021
//----------------------------------------------------

package proyecto_catedra_ayc01t_sl190836_ml190272;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Parentesis_c = 15;
  public static final int AS = 35;
  public static final int Parentesis_a = 14;
  public static final int BOOL = 57;
  public static final int Llave_c = 17;
  public static final int FROM = 11;
  public static final int Llave_a = 16;
  public static final int COLUMN = 49;
  public static final int TYPE = 101;
  public static final int GO = 88;
  public static final int OUTER = 74;
  public static final int Linea = 2;
  public static final int GROUP = 31;
  public static final int NATURAL = 45;
  public static final int SYSTEM = 86;
  public static final int Corchete_c = 19;
  public static final int TRIGGER = 90;
  public static final int TABLE = 8;
  public static final int Corchete_a = 18;
  public static final int RESET = 81;
  public static final int ROWS = 82;
  public static final int CROSS = 46;
  public static final int JOIN = 67;
  public static final int INNER = 64;
  public static final int FIRST = 58;
  public static final int LR = 69;
  public static final int DECLARE = 39;
  public static final int C_seleccion = 23;
  public static final int CONNECT = 50;
  public static final int OUT = 73;
  public static final int VIEW = 94;
  public static final int ERROR = 111;
  public static final int AFTER = 41;
  public static final int CHANGE = 103;
  public static final int THEN = 85;
  public static final int T_dato = 3;
  public static final int ILIKE = 63;
  public static final int WHEN = 95;
  public static final int INTO = 27;
  public static final int EXCEPT = 55;
  public static final int SELECT = 9;
  public static final int FULL = 60;
  public static final int OTHERS = 72;
  public static final int Op_relacional = 22;
  public static final int P_coma = 20;
  public static final int WRITE = 97;
  public static final int ALTER = 40;
  public static final int INDEX = 47;
  public static final int EXISTS = 56;
  public static final int ORDER = 30;
  public static final int UNION = 91;
  public static final int USE = 7;
  public static final int DELETE = 25;
  public static final int PRIOR = 99;
  public static final int DO = 52;
  public static final int FOR = 59;
  public static final int ADD = 44;
  public static final int ELSE = 53;
  public static final int POINT = 108;
  public static final int FUN = 106;
  public static final int SHOW = 38;
  public static final int NULL = 33;
  public static final int EOF = 0;
  public static final int INTERSECT = 65;
  public static final int WHERE = 12;
  public static final int DEFAULT = 42;
  public static final int PRINT = 78;
  public static final int FUNCTION = 61;
  public static final int Numero = 110;
  public static final int T_order = 36;
  public static final int IS = 34;
  public static final int OVER = 75;
  public static final int UNIQUE = 92;
  public static final int MODIFY = 100;
  public static final int COMILLA = 13;
  public static final int SET = 28;
  public static final int error = 1;
  public static final int START = 98;
  public static final int ON = 70;
  public static final int INTERVAL = 66;
  public static final int RULE = 83;
  public static final int IF = 68;
  public static final int SEARCH = 84;
  public static final int SEPARADOR = 107;
  public static final int CONSTRAINT_TYPE = 105;
  public static final int ONLY = 71;
  public static final int END = 54;
  public static final int DATABASE = 5;
  public static final int CHECK = 43;
  public static final int BY = 32;
  public static final int USING = 93;
  public static final int VALUES = 29;
  public static final int CREATE = 4;
  public static final int Identificador = 109;
  public static final int TRANSACTION = 89;
  public static final int All = 10;
  public static final int BEGIN = 48;
  public static final int CASE = 37;
  public static final int NEW = 76;
  public static final int RENAME = 102;
  public static final int UPDATE = 26;
  public static final int INSERT = 24;
  public static final int FOREIGN = 80;
  public static final int PRIMARY = 77;
  public static final int TO = 87;
  public static final int DROP = 6;
  public static final int WITH = 96;
  public static final int CONSTRAINT = 104;
  public static final int KEY = 79;
  public static final int Op_logico = 21;
  public static final int HAVING = 62;
  public static final int DISTINCT = 51;
}

