
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Nov 17 02:47:46 CST 2021
//----------------------------------------------------

package proyecto_catedra_ayc01t_sl190836_ml190272;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AS = 36;
  public static final int BOOL = 58;
  public static final int Llave_c = 18;
  public static final int FROM = 12;
  public static final int Llave_a = 17;
  public static final int COLUMN = 50;
  public static final int TYPE = 103;
  public static final int GO = 89;
  public static final int OUTER = 75;
  public static final int Linea = 2;
  public static final int GROUP = 32;
  public static final int NATURAL = 46;
  public static final int SYSTEM = 87;
  public static final int Corchete_c = 20;
  public static final int TRIGGER = 91;
  public static final int TABLE = 9;
  public static final int Corchete_a = 19;
  public static final int RESET = 82;
  public static final int ROWS = 83;
  public static final int CROSS = 47;
  public static final int JOIN = 68;
  public static final int INNER = 65;
  public static final int REFERENCES = 100;
  public static final int FIRST = 59;
  public static final int LR = 70;
  public static final int DECLARE = 40;
  public static final int C_seleccion = 24;
  public static final int CONNECT = 51;
  public static final int OUT = 74;
  public static final int VIEW = 95;
  public static final int ERROR = 113;
  public static final int AFTER = 42;
  public static final int CHANGE = 105;
  public static final int THEN = 86;
  public static final int T_dato = 4;
  public static final int ILIKE = 64;
  public static final int WHEN = 96;
  public static final int INTO = 28;
  public static final int EXCEPT = 56;
  public static final int SELECT = 10;
  public static final int FULL = 61;
  public static final int COMA = 111;
  public static final int OTHERS = 73;
  public static final int Op_relacional = 23;
  public static final int P_coma = 21;
  public static final int WRITE = 98;
  public static final int ALTER = 41;
  public static final int INDEX = 48;
  public static final int EXISTS = 57;
  public static final int ORDER = 31;
  public static final int UNION = 92;
  public static final int USE = 8;
  public static final int DELETE = 26;
  public static final int PRIOR = 101;
  public static final int DO = 53;
  public static final int P_c = 16;
  public static final int FOR = 60;
  public static final int P_a = 15;
  public static final int ADD = 45;
  public static final int ELSE = 54;
  public static final int POINT = 109;
  public static final int FUN = 108;
  public static final int SHOW = 39;
  public static final int NULL = 34;
  public static final int EOF = 0;
  public static final int INTERSECT = 66;
  public static final int WHERE = 13;
  public static final int DEFAULT = 43;
  public static final int PRINT = 79;
  public static final int FUNCTION = 62;
  public static final int Numero = 112;
  public static final int T_order = 37;
  public static final int IS = 35;
  public static final int Operadores = 3;
  public static final int OVER = 76;
  public static final int UNIQUE = 93;
  public static final int MODIFY = 102;
  public static final int COMILLA = 14;
  public static final int SET = 29;
  public static final int error = 1;
  public static final int START = 99;
  public static final int ON = 71;
  public static final int INTERVAL = 67;
  public static final int RULE = 84;
  public static final int IF = 69;
  public static final int SEARCH = 85;
  public static final int CONSTRAINT_TYPE = 107;
  public static final int ONLY = 72;
  public static final int END = 55;
  public static final int DATABASE = 6;
  public static final int CHECK = 44;
  public static final int BY = 33;
  public static final int USING = 94;
  public static final int VALUES = 30;
  public static final int CREATE = 5;
  public static final int Identificador = 110;
  public static final int TRANSACTION = 90;
  public static final int All = 11;
  public static final int BEGIN = 49;
  public static final int CASE = 38;
  public static final int NEW = 77;
  public static final int RENAME = 104;
  public static final int UPDATE = 27;
  public static final int INSERT = 25;
  public static final int FOREIGN = 81;
  public static final int PRIMARY = 78;
  public static final int TO = 88;
  public static final int DROP = 7;
  public static final int WITH = 97;
  public static final int CONSTRAINT = 106;
  public static final int KEY = 80;
  public static final int Op_logico = 22;
  public static final int HAVING = 63;
  public static final int DISTINCT = 52;
}

