
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Nov 12 02:42:02 CST 2021
//----------------------------------------------------

package proyecto_catedra_ayc01t_sl190836_ml190272;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int WHERE = 12;
  public static final int FROM = 11;
  public static final int Parentesis_c = 15;
  public static final int Parentesis_a = 14;
  public static final int SELECT = 9;
  public static final int Numero = 25;
  public static final int Corchete_c = 19;
  public static final int ERROR = 26;
  public static final int Corchete_a = 18;
  public static final int Identificador = 24;
  public static final int Llave_c = 17;
  public static final int All = 10;
  public static final int Llave_a = 16;
  public static final int TABLE = 8;
  public static final int Op_relacional = 22;
  public static final int P_coma = 20;
  public static final int T_dato = 3;
  public static final int CREATE = 4;
  public static final int EOF = 0;
  public static final int C_seleccion = 23;
  public static final int DATABASE = 5;
  public static final int COMILLA = 13;
  public static final int DROP = 6;
  public static final int Linea = 2;
  public static final int error = 1;
  public static final int Op_logico = 21;
  public static final int USE = 7;
}

